package vsec.com.slockandroid.generalModels

enum class PasswordScore {
    WEAK, AVERAGE, STRONG, MARVELOUS
}

enum class ButtonState {
    EMAIL_VALID,
    EMAIL_EQUAL,
    FIRST_NAME_VALID,
    LAST_NAME_VALID,
    PASSWORD_VALID,
    PASSWORD_EQUAL,
    LOCK_NAME_VALID,
    REGISTERABLE_LOCK_FOUND,
    LOGIN_BUTTON_OK,
    CHANGE_PASSWORD_BUTTON_OK,
    LOCK_DESCRIPTION_VALID,
    START_DATE_VALID,
    END_DATE_VALID,

    LOCK_PRODUCTKEY_VALID
}

